// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: proto/dog/dog.proto

package dog

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	person "petshop/proto/person"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Breed int32

const (
	Breed_UNKNOWN_BREED    Breed = 0
	Breed_LABRADOR         Breed = 1
	Breed_GERMAN_SHEPHERD  Breed = 2
	Breed_GOLDEN_RETRIEVER Breed = 3
	Breed_BULLDOG          Breed = 4
	Breed_BEAGLE           Breed = 5
	Breed_POODLE           Breed = 6
	Breed_BOXER            Breed = 7
)

// Enum value maps for Breed.
var (
	Breed_name = map[int32]string{
		0: "UNKNOWN_BREED",
		1: "LABRADOR",
		2: "GERMAN_SHEPHERD",
		3: "GOLDEN_RETRIEVER",
		4: "BULLDOG",
		5: "BEAGLE",
		6: "POODLE",
		7: "BOXER",
	}
	Breed_value = map[string]int32{
		"UNKNOWN_BREED":    0,
		"LABRADOR":         1,
		"GERMAN_SHEPHERD":  2,
		"GOLDEN_RETRIEVER": 3,
		"BULLDOG":          4,
		"BEAGLE":           5,
		"POODLE":           6,
		"BOXER":            7,
	}
)

func (x Breed) Enum() *Breed {
	p := new(Breed)
	*p = x
	return p
}

func (x Breed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Breed) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dog_dog_proto_enumTypes[0].Descriptor()
}

func (Breed) Type() protoreflect.EnumType {
	return &file_proto_dog_dog_proto_enumTypes[0]
}

func (x Breed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Breed.Descriptor instead.
func (Breed) EnumDescriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{0}
}

type Dog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age   int32          `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Toys  []string       `protobuf:"bytes,5,rep,name=toys,proto3" json:"toys,omitempty"`
	Owner *person.Person `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Breed Breed          `protobuf:"varint,7,opt,name=breed,proto3,enum=dog.Breed" json:"breed,omitempty"`
}

func (x *Dog) Reset() {
	*x = Dog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dog) ProtoMessage() {}

func (x *Dog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dog.ProtoReflect.Descriptor instead.
func (*Dog) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{0}
}

func (x *Dog) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dog) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Dog) GetToys() []string {
	if x != nil {
		return x.Toys
	}
	return nil
}

func (x *Dog) GetOwner() *person.Person {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Dog) GetBreed() Breed {
	if x != nil {
		return x.Breed
	}
	return Breed_UNKNOWN_BREED
}

type GetDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDogRequest) Reset() {
	*x = GetDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogRequest) ProtoMessage() {}

func (x *GetDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogRequest.ProtoReflect.Descriptor instead.
func (*GetDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{1}
}

func (x *GetDogRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *GetDogResponse) Reset() {
	*x = GetDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDogResponse) ProtoMessage() {}

func (x *GetDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDogResponse.ProtoReflect.Descriptor instead.
func (*GetDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{2}
}

func (x *GetDogResponse) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type ListDogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog []*Dog `protobuf:"bytes,1,rep,name=dog,proto3" json:"dog,omitempty"`
}

func (x *ListDogsResponse) Reset() {
	*x = ListDogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDogsResponse) ProtoMessage() {}

func (x *ListDogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDogsResponse.ProtoReflect.Descriptor instead.
func (*ListDogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{3}
}

func (x *ListDogsResponse) GetDog() []*Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type CreateDogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dog *Dog `protobuf:"bytes,1,opt,name=dog,proto3" json:"dog,omitempty"`
}

func (x *CreateDogRequest) Reset() {
	*x = CreateDogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogRequest) ProtoMessage() {}

func (x *CreateDogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogRequest.ProtoReflect.Descriptor instead.
func (*CreateDogRequest) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDogRequest) GetDog() *Dog {
	if x != nil {
		return x.Dog
	}
	return nil
}

type CreateDogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDogResponse) Reset() {
	*x = CreateDogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dog_dog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDogResponse) ProtoMessage() {}

func (x *CreateDogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dog_dog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDogResponse.ProtoReflect.Descriptor instead.
func (*CreateDogResponse) Descriptor() ([]byte, []int) {
	return file_proto_dog_dog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDogResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_dog_dog_proto protoreflect.FileDescriptor

var file_proto_dog_dog_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x67, 0x2f, 0x64, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x67, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x03, 0x44, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x79, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x6f, 0x79, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x05, 0x62, 0x72,
	0x65, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x64, 0x6f, 0x67, 0x2e,
	0x42, 0x72, 0x65, 0x65, 0x64, 0x52, 0x05, 0x62, 0x72, 0x65, 0x65, 0x64, 0x22, 0x1f, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64,
	0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x2e, 0x0a, 0x10, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64,
	0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x2e, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x03, 0x64, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x64,
	0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x23, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x2a, 0x83, 0x01, 0x0a, 0x05, 0x42, 0x72, 0x65, 0x65, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x42, 0x52, 0x45, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x4c, 0x41, 0x42, 0x52, 0x41, 0x44, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x47,
	0x45, 0x52, 0x4d, 0x41, 0x4e, 0x5f, 0x53, 0x48, 0x45, 0x50, 0x48, 0x45, 0x52, 0x44, 0x10, 0x02,
	0x12, 0x14, 0x0a, 0x10, 0x47, 0x4f, 0x4c, 0x44, 0x45, 0x4e, 0x5f, 0x52, 0x45, 0x54, 0x52, 0x49,
	0x45, 0x56, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x55, 0x4c, 0x4c, 0x44, 0x4f,
	0x47, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x45, 0x41, 0x47, 0x4c, 0x45, 0x10, 0x05, 0x12,
	0x0a, 0x0a, 0x06, 0x50, 0x4f, 0x4f, 0x44, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x42,
	0x4f, 0x58, 0x45, 0x52, 0x10, 0x07, 0x32, 0xb6, 0x01, 0x0a, 0x0a, 0x44, 0x6f, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x12,
	0x12, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x6f, 0x67, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x64,
	0x6f, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67,
	0x12, 0x15, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x13, 0x5a, 0x11, 0x70, 0x65, 0x74, 0x73, 0x68, 0x6f, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x64, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dog_dog_proto_rawDescOnce sync.Once
	file_proto_dog_dog_proto_rawDescData = file_proto_dog_dog_proto_rawDesc
)

func file_proto_dog_dog_proto_rawDescGZIP() []byte {
	file_proto_dog_dog_proto_rawDescOnce.Do(func() {
		file_proto_dog_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dog_dog_proto_rawDescData)
	})
	return file_proto_dog_dog_proto_rawDescData
}

var file_proto_dog_dog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dog_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_dog_dog_proto_goTypes = []interface{}{
	(Breed)(0),                // 0: dog.Breed
	(*Dog)(nil),               // 1: dog.Dog
	(*GetDogRequest)(nil),     // 2: dog.GetDogRequest
	(*GetDogResponse)(nil),    // 3: dog.GetDogResponse
	(*ListDogsResponse)(nil),  // 4: dog.ListDogsResponse
	(*CreateDogRequest)(nil),  // 5: dog.CreateDogRequest
	(*CreateDogResponse)(nil), // 6: dog.CreateDogResponse
	(*person.Person)(nil),     // 7: person.Person
	(*empty.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_proto_dog_dog_proto_depIdxs = []int32{
	7, // 0: dog.Dog.owner:type_name -> person.Person
	0, // 1: dog.Dog.breed:type_name -> dog.Breed
	1, // 2: dog.GetDogResponse.dog:type_name -> dog.Dog
	1, // 3: dog.ListDogsResponse.dog:type_name -> dog.Dog
	1, // 4: dog.CreateDogRequest.dog:type_name -> dog.Dog
	2, // 5: dog.DogService.GetDog:input_type -> dog.GetDogRequest
	8, // 6: dog.DogService.ListDogs:input_type -> google.protobuf.Empty
	5, // 7: dog.DogService.CreateDog:input_type -> dog.CreateDogRequest
	3, // 8: dog.DogService.GetDog:output_type -> dog.GetDogResponse
	4, // 9: dog.DogService.ListDogs:output_type -> dog.ListDogsResponse
	6, // 10: dog.DogService.CreateDog:output_type -> dog.CreateDogResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_dog_dog_proto_init() }
func file_proto_dog_dog_proto_init() {
	if File_proto_dog_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dog_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_dog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_dog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_dog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dog_dog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dog_dog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dog_dog_proto_goTypes,
		DependencyIndexes: file_proto_dog_dog_proto_depIdxs,
		EnumInfos:         file_proto_dog_dog_proto_enumTypes,
		MessageInfos:      file_proto_dog_dog_proto_msgTypes,
	}.Build()
	File_proto_dog_dog_proto = out.File
	file_proto_dog_dog_proto_rawDesc = nil
	file_proto_dog_dog_proto_goTypes = nil
	file_proto_dog_dog_proto_depIdxs = nil
}
